### ISSUE TITLE
How can I obtain the data set? 

### ISSUE THREAD

**Issue by BrightMoonStar** [Junxix/S2I#1]
Excuse me. How can I obtain the data set? Thank you for your reply and assistance!

**Comment by Galaxies99** [comment]
In the paper, we use the RoboMimic multi-human (MH) dataset. You can download them from its official page.

Notice that we use the `v0.2` branch to align with the original RoboMimic paper (CoRL 2021), with the RoboSuite `offline_study` branch, as mentioned in the RoboMimic documentation.

https://robomimic.github.io/docs/v0.2/datasets/robomimic_v0.1.html
